[package]
name = "dynamo-it"
version = "0.1.0"
authors = ["Russell Cohen <rcoh@amazon.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
smithy-types = { path = "../build/aws-sdk/smithy-types" }
dynamodb = { version = "0.0.1", path = "../build/aws-sdk/dynamodb"}
io-v0 = { path = "../build/aws-sdk/io-v0" }
aws-hyper = { path = "../build/aws-sdk/aws-hyper"}
tokio = { version = "1", features = ["full"] }
rand  = "0.7.3"
bytes = "1"
hyper = "0.14.2"


# these are just for the stub implementation
operation = { path = "../build/aws-sdk/operation"}
auth = { path = "../build/aws-sdk/auth" }
http = "0.2.3"
